version: "3"
services:

  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: odontosys
      POSTGRES_DB: odontosys
    ports:
      - 5440:5432
    volumes:
      - ./postgres-data-odontosys:/bitnami/postgresql/data